# Generated by Django 4.2.2 on 2023-06-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('pan_card_number', models.CharField(max_length=100)),
                ('uan_number', models.CharField(max_length=100)),
                ('pf_number', models.CharField(max_length=100)),
                ('paid_days', models.CharField(max_length=100)),
                ('paid_leaves', models.CharField(max_length=100)),
                ('date_of_jioning', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
