# Generated by Django 4.2.2 on 2023-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.IntegerField(default=0)),
                ('house_rent_allowances', models.IntegerField(default=0)),
                ('medical_allowance', models.IntegerField(default=0)),
                ('conveyance', models.IntegerField(default=0)),
                ('special_allowance', models.IntegerField(default=0)),
                ('phone_allowance', models.IntegerField(default=0)),
                ('salary_arrears', models.IntegerField(default=0)),
                ('employee_referral_scheme', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
            ],
        ),
    ]
